config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#welcome'
  get "about" =>'static_pages#about'
  get "contact" =>'static_pages#contact'
  
  get  'puppies/' => 'puppies#index'
  post 'puppies/' => 'puppies#create'
  get  'puppies/new' => 'puppies#new'
  get  'puppies/:id/edit' => 'puppies#edit', as: 'edit_puppy'
  get  'puppies/:id' => 'puppies#show', as: 'puppy'
  patch 'puppies/:id' => 'puppies#update'
  delete 'puppies/:id' => 'puppies#destroy'

end

app/models/puppy.rb
class Puppy < ActiveRecord::Base


	validates :name, uniqueness:{ case_sensitive: false}, presence: true
	validates :bio, presence: true
	validates :age, presence: true
	validates :breed, presence: true
	validates :image_url, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/puppies_controller.rb
class PuppiesController < ApplicationController


  def index
  	@puppies = Puppy.all
  end
  
  def new
  	@puppy = Puppy.new
  end

  def create
  	puts puppy_params
  	@puppy = Puppy.create(puppy_params)
  	if @puppy.save
  	  redirect_to puppies_path, notice: 'Puppy has been added!'
  	else
  	  render :new
  	end
  end

  def edit
  	@puppy = Puppy.find(params[:id])
  end

  def show
  	@puppy = Puppy.find_by(id: params[:id])
  end

  def update
  	@puppy = Puppy.find_by(id: params[:id])
  	@puppy.update(puppy_params)
  	if @puppy.save
  		redirect_to puppy_path(@puppy), notice: 'Puppy has been updated!'
  	else
  		render :edit
  	end
  end

  def destroy
  	@puppy = Puppy.find_by(id: params[:id])
  	@puppy.destroy
  	redirect_to puppies_path
  end

private

  def puppy_params
  	params.require(:puppy).permit(
  		:name,
  		:age,
  		:bio,
  		:breed,
  		:image_url
  		)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def welcome

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PuppyCrudApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="navbar navbar-default navbar-fixed-top">
		<div class="container">
      <%= link_to "Home", root_path, class:"navbar-text" %> 
      <%= link_to "See All Puppies!", puppies_path, class:"navbar-text" %> 
      <%= link_to "About", "/about", class:"navbar-text" %> 
			<%= link_to "Contact", "/contact",class:"navbar-text" %>
		</div>
  </div>
  <br>
  
  <div class="container main">
    <% if notice %>
      <div class="alert alert-success errors">
        <%= notice %>
      </div>
    <% end %>
    <%= yield %>	
  </div>

</body>
</html>

app/views/puppies/_errors.html.erb
<% if instance.errors.any? %>
<ul class="alert alert-danger">
  <% instance.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

app/views/puppies/_form.html.erb
<%= form_for(@puppy, html:{class:"form-horizontal", role:"form"}) do |f| %>
	<%= render partial:'puppies/errors', locals:{instance:@puppy}  %>
	<div class="form-group">
		<%= f.label :name, class:"col-md-2"  %>
		<div class="col-sm-7">
			<%= f.text_field :name, class:"form-control" %>
		</div>
	</div>

	<div class="form-group">
		<%= f.label :breed, class:"col-md-2"  %>
		<div class="col-sm-7">
			<%= f.text_field :breed, class:"form-control" %>
		</div>
	</div>

	<div class="form-group">
		<%= f.label :age, class:"col-md-2"  %>
		<div class="col-sm-7">
			<%= f.number_field :age, class:"form-control", placeholder:"age in months" %>
		</div>
	</div>

	<div class="form-group">
		<%= f.label :bio, class:"col-md-2"  %>
		<div class="col-sm-7">
			<%= f.text_field :bio, class:"form-control" %>
		</div>
	</div>

	<div class="form-group">
		<%= f.label :image_url, class:"col-md-2"  %>
		<div class="col-sm-7">
			<%= f.text_field :image_url, class:"form-control" %>
		</div>
	</div>

	<div class="actions col-sm-offset-2">
		<%= f.submit class:"btn btn-primary" %>
		<%= link_to 'Cancel', puppies_path, class:"btn btn-default" %>
	</div>
<% end %>

app/views/puppies/edit.html.erb
<h1 class="page-header">Edit Puppy</h1>

<%= render 'form'  %>

app/views/puppies/index.html.erb
<%= link_to "Add A New Puppy", puppies_new_path, class:"btn btn-info" %>
<div class="row">
  <% @puppies.each do |puppy| %>
    <div class="col-sm-6 col-md-4" style="height:436.667px;">
      <div class="thumbnail">
        <%= image_tag(puppy.image_url) %>
        <div class="caption">
          <h3><%= link_to "#{puppy.name}", puppy_path(puppy) %></h3>
          <p><%= puppy.breed %></p>
          <p><%= puppy.age %></p>
          
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/puppies/new.html.erb
<h1 class="page-header">Add a new puppy</h1>

<%= render 'form'  %>

app/views/puppies/show.html.erb
<h1 class="page-header"><%= @puppy.name %></h1>




<div class="row">
 <div class="col-sm-6 col-md-4">

     <%= image_tag(@puppy.image_url, class:"thumbnail profile_img") %>


 </div>
 <div class="caption col-sm-6 col-md-4 pull-right">
       <h3><%= @puppy.name %></h3>
       <h5>Age:<%= @puppy.age  %></h5>
       <h5>Breed:<%= @puppy.breed %></h5>
       <h5>Bio:</h5><p><%= @puppy.bio %></p>
       <%= link_to "Edit", edit_puppy_path(@puppy), class:"btn btn-primary" %>
       <%= link_to "Adopted", @puppy, method: :delete, data:{alert:"are you sure?"} ,class:"btn btn-default" %>
 </div>
</div>




<p>

</p>

app/views/static_pages/about.html.erb
<h1 class="page-header">About Local Puppy Rescue</h1>

<p>Local puppy rescue is all about rescuing the most puppies possible and connecting them to loving homes and families.</p>

<p>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris id leo leo. Aliquam erat volutpat. Praesent varius, eros sit amet suscipit vehicula, nisl neque venenatis sem, sit amet dignissim nisl augue non ex. Curabitur semper sagittis odio vel varius. Curabitur dignissim tincidunt viverra. Etiam sagittis suscipit ex a posuere. Fusce vitae enim eros. Proin nec porttitor nisl. Nam sed ex vehicula, volutpat tortor in, consectetur tellus. Donec maximus feugiat leo vel malesuada. Vestibulum ullamcorper facilisis nunc, in iaculis ex lacinia vel. Sed sagittis viverra augue, sed semper lectus commodo at. Duis bibendum nec nunc eu finibus. Vestibulum pulvinar bibendum lorem non consectetur.
</p>
<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris id leo leo. Aliquam erat volutpat. Praesent varius, eros sit amet suscipit vehicula, nisl neque venenatis sem, sit amet dignissim nisl augue non ex. Curabitur semper sagittis odio vel varius. Curabitur dignissim tincidunt viverra. Etiam sagittis suscipit ex a posuere. Fusce vitae enim eros. Proin nec porttitor nisl. Nam sed ex vehicula, volutpat tortor in, consectetur tellus. Donec maximus feugiat leo vel malesuada. Vestibulum ullamcorper facilisis nunc, in iaculis ex lacinia vel. Sed sagittis viverra augue, sed semper lectus commodo at. Duis bibendum nec nunc eu finibus. Vestibulum pulvinar bibendum lorem non consectetur.

Nulla feugiat auctor nibh a vehicula. Suspendisse molestie convallis nunc id accumsan. Etiam hendrerit lectus libero, vitae malesuada augue egestas in. Vivamus finibus volutpat elit, in tempus nunc tristique non. Proin condimentum urna eros, eget scelerisque mi porta nec. Donec hendrerit, nunc et ornare feugiat, libero risus porttitor velit, quis volutpat risus justo nec purus. Proin auctor leo mattis mollis suscipit. Nunc risus odio, hendrerit eu faucibus eu, elementum ac libero.
  <h3>Adopt a puppy today!</h3>
</p>

<p>
  <%= image_tag("http://cuteanimalpicturesandvideos.com/wp-content/uploads/super-cute-puppy-look-awww-photo.jpg") %>
</p>

app/views/static_pages/contact.html.erb
<h1 class="page-header">Contact Information</h1>
<p>San Francisco SPCA</p>
<p>201 Alabama Street</p>
<p>San Francisco CA 94103</p>
<p>415.554.3000</p>

app/views/static_pages/welcome.html.erb
<div class="cover responsive">
	<div id="message" class="col-sm-6 col-sm-offset-1">
	  <h1 id="mainHeader">Local Puppy Rescue</h1>
	  <p>Welcome to the local puppy rescue! Save a puppy today!</p>
		<p>
			<%= link_to "Learn More!", "/about", id:"learnMore", class:"btn btn-primary btn-lg" %>
		</p>
	</div>
</div>